import type { TranslatorKey } from "@/types";

export type OptionsPanelProps = {
  detectionResolution: string;
  textDetector: string;
  ocr: string;
  renderFont: string;
  renderTextDirection: string;
  letterCase: "none" | "uppercase" | "lowercase";
  translator: TranslatorKey;
  summaryModel: string;
  targetLanguage: string;
  translationQuality: "fast" | "professional";
  draftTranslator?: TranslatorKey | "";
  inpaintingSize: string;
  customUnclipRatio: number;
  customBoxThreshold: number;
  customOcrProb?: number;
  maskDilationOffset: number;
  bubbleDetection: boolean;
  bubbleConfidence: number;
  inpainter: string;
  colorizer: string;
  colorizeOnly: boolean;
  colorizationSize: string;
  denoiseSigma: number;
  colorThreshold: number;
  upscaler: string;
  upscaleRatio: string;
  revertUpscaling: boolean;
  rememberSettings: boolean;
  translationBatchSize: number;

  setDetectionResolution: (val: string) => void;
  setTextDetector: (val: string) => void;
  setOcr: (val: string) => void;
  setRenderFont: (val: string) => void;
  setRenderTextDirection: (val: string) => void;
  setLetterCase: (val: "none" | "uppercase" | "lowercase") => void;
  setTranslator: (val: TranslatorKey) => void;
  setSummaryModel: (val: string) => void;
  setTargetLanguage: (val: string) => void;
  setTranslationQuality: (val: "fast" | "professional") => void;
  setDraftTranslator?: (val: TranslatorKey | "") => void;
  setInpaintingSize: (val: string) => void;
  setCustomUnclipRatio: (val: number) => void;
  setCustomBoxThreshold: (val: number) => void;
  setCustomOcrProb: (val: number | undefined) => void;
  setMaskDilationOffset: (val: number) => void;
  setBubbleDetection: (val: boolean) => void;
  setBubbleConfidence: (val: number) => void;
  setInpainter: (val: string) => void;
  setColorizer: (val: string) => void;
  setColorizeOnly: (val: boolean) => void;
  setColorizationSize: (val: string) => void;
  setDenoiseSigma: (val: number) => void;
  setColorThreshold: (val: number) => void;
  setUpscaler: (val: string) => void;
  setUpscaleRatio: (val: string) => void;
  setRevertUpscaling: (val: boolean) => void;
  setRememberSettings: (val: boolean) => void;
  setTranslationBatchSize: (val: number) => void;
};
